// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkevvnZVxlLBOctOX6UJrARK_Cvjv3NBg',
    appId: '1:1093432723763:web:f0810b6f87aba677485646',
    messagingSenderId: '1093432723763',
    projectId: 'nongkiyuk-6763e',
    authDomain: 'nongkiyuk-6763e.firebaseapp.com',
    databaseURL: 'https://nongkiyuk-6763e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nongkiyuk-6763e.firebasestorage.app',
    measurementId: 'G-TZJH2B5BS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNLSvd8lXRI6XahRlxpgiitvvDeDZHo3E',
    appId: '1:1093432723763:android:522abc60b5dd1b74485646',
    messagingSenderId: '1093432723763',
    projectId: 'nongkiyuk-6763e',
    databaseURL: 'https://nongkiyuk-6763e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nongkiyuk-6763e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQplQ-OzmzK1JLs79Ni9c98HwqkI69Ivw',
    appId: '1:1093432723763:ios:f70b67cb8db26600485646',
    messagingSenderId: '1093432723763',
    projectId: 'nongkiyuk-6763e',
    databaseURL: 'https://nongkiyuk-6763e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nongkiyuk-6763e.firebasestorage.app',
    iosBundleId: 'com.example.nongkiYuk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQplQ-OzmzK1JLs79Ni9c98HwqkI69Ivw',
    appId: '1:1093432723763:ios:f70b67cb8db26600485646',
    messagingSenderId: '1093432723763',
    projectId: 'nongkiyuk-6763e',
    databaseURL: 'https://nongkiyuk-6763e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nongkiyuk-6763e.firebasestorage.app',
    iosBundleId: 'com.example.nongkiYuk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkevvnZVxlLBOctOX6UJrARK_Cvjv3NBg',
    appId: '1:1093432723763:web:26d5467590075567485646',
    messagingSenderId: '1093432723763',
    projectId: 'nongkiyuk-6763e',
    authDomain: 'nongkiyuk-6763e.firebaseapp.com',
    databaseURL: 'https://nongkiyuk-6763e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nongkiyuk-6763e.firebasestorage.app',
    measurementId: 'G-ZZ8Q12W6LR',
  );

}